import { createHash, type Hash } from "node:crypto";

export const SOURCE_MANIFEST_VERSION = 1;
export interface SourceCompetitionFingerprint { competitionId: string; competitionMetadataHash: string; resultCount: number; resultsHash: string; attemptCount: number; attemptsHash: string; year: number; }
export interface SourceYearFingerprint { competitionCount: number; competitionIds: string[]; fingerprint: string; year: number; }
export interface SourceManifest { exportId: string; generatedAt: string; version: number; competitions: Record<string, SourceCompetitionFingerprint>; years: Record<string, SourceYearFingerprint>; dimensions: { attemptsHash: string; attemptsChanged: boolean; personsHash: string; personsChanged: boolean; }; }
export interface SourceManifestComparison { dirtyCompetitionIds: string[]; dirtyYears: number[]; missingPreviousManifest: boolean; attemptsChanged: boolean; personsChanged: boolean; reasons: string[]; }
interface CompetitionState { competitionId: string; year: number; competitionMetadataHash: string; results: Hash; attempts: Hash; resultCount: number; attemptCount: number; lastResultId?: number; }
function canonical(value: unknown): string { if (value === null || value === undefined) return "null"; if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (typeof value === "object") return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, entry]) => `${JSON.stringify(key)}:${canonical(entry)}`).join(",")}}`; return JSON.stringify(value); }
function digest(): Hash { return createHash("sha256"); }
function append(hash: Hash, value: unknown): void { const encoded = canonical(value); hash.update(`${Buffer.byteLength(encoded, "utf8")}:`); hash.update(encoded); hash.update(";"); }
function finalDigest(hash: Hash): string { return hash.copy().digest("hex"); }
function yearFingerprint(entries: readonly SourceCompetitionFingerprint[]): string { const hash = digest(); for (const entry of [...entries].sort((a, b) => a.competitionId.localeCompare(b.competitionId))) append(hash, { competitionId: entry.competitionId, competitionMetadataHash: entry.competitionMetadataHash, resultsHash: entry.resultsHash, attemptsHash: entry.attemptsHash, resultCount: entry.resultCount, attemptCount: entry.attemptCount }); return finalDigest(hash); }

export class SourceManifestBuilder {
  private readonly competitions = new Map<string, CompetitionState>();
  private readonly persons: Array<{ personKey: string; person: unknown }> = [];
  private readonly attempts = digest();
  constructor(private readonly exportId: string) {}
  addCompetition(competitionId: string, year: number, metadata: unknown): void { if (!competitionId || !Number.isInteger(year)) throw new Error("Competition fingerprints require an ID and integer year"); if (this.competitions.has(competitionId)) throw new Error(`Duplicate competition ${competitionId}`); const metadataHash = digest(); append(metadataHash, metadata); this.competitions.set(competitionId, { competitionId, year, competitionMetadataHash: finalDigest(metadataHash), results: digest(), attempts: digest(), resultCount: 0, attemptCount: 0 }); }
  addResult(competitionId: string, resultId: number, result: unknown): void { const competition = this.competitions.get(competitionId); if (!competition) throw new Error(`Unknown competition ${competitionId}`); if (competition.lastResultId !== undefined && resultId < competition.lastResultId) throw new Error(`Results for ${competitionId} are not ordered by stable result ID`); competition.lastResultId = resultId; append(competition.results, { resultId, result }); competition.resultCount += 1; }
  addAttempt(competitionId: string, resultId: number, attemptNumber: number, attempt: unknown): void { const competition = this.competitions.get(competitionId); if (!competition) throw new Error(`Unknown competition ${competitionId}`); append(competition.attempts, { resultId, attemptNumber, attempt }); append(this.attempts, { resultId, attemptNumber, attempt }); competition.attemptCount += 1; }
  addRawAttempt(resultId: number, attemptNumber: number, attempt: unknown): void { append(this.attempts, { resultId, attemptNumber, attempt }); }
  addPerson(personKey: string, person: unknown): void { this.persons.push({ personKey, person }); }
  build(previous?: SourceManifest): SourceManifest { const competitions: Record<string, SourceCompetitionFingerprint> = {}; const byYear = new Map<number, SourceCompetitionFingerprint[]>(); for (const state of this.competitions.values()) { const entry = { competitionId: state.competitionId, competitionMetadataHash: state.competitionMetadataHash, resultCount: state.resultCount, resultsHash: finalDigest(state.results), attemptCount: state.attemptCount, attemptsHash: finalDigest(state.attempts), year: state.year }; competitions[entry.competitionId] = entry; byYear.set(entry.year, [...(byYear.get(entry.year) ?? []), entry]); } const years: Record<string, SourceYearFingerprint> = {}; for (const [year, entries] of byYear) years[String(year)] = { year, competitionCount: entries.length, competitionIds: entries.map((entry) => entry.competitionId).sort((a, b) => a.localeCompare(b)), fingerprint: yearFingerprint(entries) }; const personHash = digest(); for (const person of [...this.persons].sort((a, b) => a.personKey.localeCompare(b.personKey))) append(personHash, person); const personsHash = finalDigest(personHash); const attemptsHash = finalDigest(this.attempts); return { version: SOURCE_MANIFEST_VERSION, exportId: this.exportId, generatedAt: new Date().toISOString(), competitions, years, dimensions: { personsHash, personsChanged: previous?.dimensions.personsHash !== personsHash, attemptsHash, attemptsChanged: previous?.dimensions.attemptsHash !== attemptsHash } }; }
}

export function compareSourceManifests(current: SourceManifest, previous?: SourceManifest, currentYear = new Date(current.exportId).getUTCFullYear()): SourceManifestComparison { if (!previous || previous.version !== current.version) return { dirtyCompetitionIds: Object.keys(current.competitions).sort(), dirtyYears: Object.keys(current.years).map(Number).sort((a, b) => a - b), missingPreviousManifest: !previous, attemptsChanged: true, personsChanged: true, reasons: [previous ? "manifest-version-changed" : "manifest-missing"] }; const dirtyCompetitionIds = new Set<string>(); const reasons: string[] = []; for (const id of new Set([...Object.keys(current.competitions), ...Object.keys(previous.competitions)])) if (canonical(current.competitions[id]) !== canonical(previous.competitions[id])) dirtyCompetitionIds.add(id); const attemptsChanged = current.dimensions.attemptsHash !== previous.dimensions.attemptsHash; const personsChanged = current.dimensions.personsHash !== previous.dimensions.personsHash; if (attemptsChanged) reasons.push("attempts-changed"); if (personsChanged) reasons.push("persons-changed"); const dirtyYears = new Set<number>([currentYear]); for (const year of new Set([...Object.keys(current.years).map(Number), ...Object.keys(previous.years).map(Number)])) if (current.years[String(year)]?.fingerprint !== previous.years[String(year)]?.fingerprint) dirtyYears.add(year); for (const id of dirtyCompetitionIds) { const year = current.competitions[id]?.year ?? previous.competitions[id]?.year; if (year !== undefined) dirtyYears.add(year); } if (attemptsChanged) { for (const year of Object.keys(current.years).map(Number)) dirtyYears.add(year); reasons.push("all-years-invalidated-by-attempts"); } if (personsChanged) reasons.push("person-dependent-projections-invalidated"); return { dirtyCompetitionIds: [...dirtyCompetitionIds].sort(), dirtyYears: [...dirtyYears].sort((a, b) => a - b), missingPreviousManifest: false, attemptsChanged, personsChanged, reasons }; }
