CREATE TABLE IF NOT EXISTS feed_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  export_version VARCHAR(64) NOT NULL,
  interesting_result_id BIGINT UNSIGNED NOT NULL,
  interesting_entity_id VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  event_id VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  event_name VARCHAR(128) NOT NULL,
  result_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  stat_kind VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  region_scope VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  region_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  gender CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NULL,
  stat_year SMALLINT UNSIGNED NULL,
  title VARCHAR(255) NOT NULL,
  explore_url VARCHAR(1024) NOT NULL,
  world_rank INT UNSIGNED NULL,
  continent_rank INT UNSIGNED NULL,
  country_rank INT UNSIGNED NULL,
  ranking_list_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP (6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_feed_items_export_result (export_version, interesting_result_id),
  INDEX idx_feed_items_export_sort (export_version, region_scope, region_id, id),
  INDEX idx_feed_items_result (interesting_result_id),
  INDEX idx_feed_items_ranking_list (ranking_list_key)
);
